### ISSUE TITLE
geofire swift import no module found

### ISSUE THREAD

**Issue by Now2407** [firebase/geofire-objc#20] opened 2015-08-30 00:33 UTC
i tried using Cocoa pods and manual installing the frameworks but get the error "no module found" when i try to import it in my swift Project
<img width="475" alt="screen shot 2015-08-29 at 5 32 10 pm" src="https://cloud.githubusercontent.com/assets/6015402/9565161/f236c4b4-4e73-11e5-87f6-7ce21ce03fda.png">
I have no idea what is wrong with it?!

**Comment by jdimond** [comment] 2015-09-03 11:56
Do you have the contents of the Podfile you used?

**Comment by alvivi** [comment] 2015-09-04 16:00
Same here. There is no way to import GeoFire (using XCode 7 beta 6)

**Comment by mcdonamp** [comment] 2015-09-04 20:22
Have either of you tried `use_frameworks!` as an option in your Podfile?

I've got the following Podfile working to import GeoFire:

```
platform :ios, '8.0'
use_frameworks!

pod 'GeoFire', '~>1.1'

target 'GeofireTest' do

end
```

Make sure you're using a version of Cocoapods > 0.36 (as I believe it was [introduced there](http://blog.cocoapods.org/CocoaPods-0.36/)). We're working on fixing issues with dynamic libs in iOS 8+ as well as module maps to better support Swift.

If this is confirmed that `use_frameworks!` solves the issue, I'll update the README with this info.

**Comment by alvivi** [comment] 2015-09-09 06:59
@mcdonamp moving to cocoapods is not a solution. We managed to rebuild the project and compile a proper binary. We ported the project to Carthage, here is the [repository](https://github.com/meetizer/geofire).

**Comment by mcdonamp** [comment] 2015-09-09 15:37
Ah, interesting. We've considered Carthage support, but haven't seen many requests for it. Is there a reason you prefer Carthage to Cocoapods? If there are compelling reasons, we'd be more inclined to officially support it.

**Comment by alvivi** [comment] 2015-09-09 21:06
@mcdonamp well, try to create a multi-target project using a bunch of bleeding edge swift 2.0 libraries using cocopods. Complex projects tend to have multiple targets, multiple builds schemes, build configurations, etc. Cocoapods modify your project (and workspace), adding to them an extra layer of complexity. Carthage is [plain simple](https://github.com/Carthage/Carthage#differences-between-carthage-and-cocoapods).

**Comment by mcdonamp** [comment] 2015-09-09 21:16
@alvivi yep, agree with that, which is why we're investigating Carthage support (it's definitely increased in our queue since Swift 2.0 and issues with Cocoapods not supporting dependencies well). I know Cocoapods is working on better Swift support, but they have a ways to go. In our mind, Carthage is the power tool, while Cocoapods is the solution that works in ~90% of the situations with half of the effort.

I'll download Beta 6 and give it a shot to see what I can find. In the meantime, feel free to submit a PR converting Geofire to Carthage and we're happy to review and merge. Sounds like it could benefit a core group of folks like yourself :)

**Comment by sammy-SC** [comment] 2015-09-17 00:27
@mcdonamp I would like to see Carthage support as well. are PRs welcome?

**Comment by mcdonamp** [comment] 2015-09-17 01:21
@sammy-SC PR's are always welcome :+1:

**Comment by sammy-SC** [comment] 2015-09-22 22:57
Hello @mcdonamp,

I have been investigating Carthage support for Geofire however I came to a conclusion that without Firebase (Geofire's dependency) supporting Carthage it is not possible for Geofire to support Carthage without Firebase being included in git.

https://github.com/Carthage/Carthage/issues/486 for further information on Carthage <-> Cocoapods

**Comment by mcdonamp** [comment] 2015-09-23 04:13
@sammy-SC thanks for the heads up. Yes, it's difficult that Firebase is currently closed source, but since we provide the framework (which is ultimately what Carthage provides), it ends up doing the same thing. This is what it looks like @alvivi ended up doing--just pulling down the framework and then using it later. Not as flexible as full Carthage support though :/

I think another challenge with Carthage is that it's iOS 8+ only, since it's dynamic frameworks only. iOS 7 still accounts for ~30-35% of the market.

I think we'll be holding off for a little more (given some of the above reasons), but it's something were definitely still interested in, as Carthage offers significantly more flexibility than Cocoapods.

**Closed by mcdonamp** 2015-09-23 04:13 UTC
Labels: enhancement
