### ISSUE TITLE
No support for firebase 7.0.0

### ISSUE THREAD

**Issue by thatguyhampton** [firebase/geofire-objc#144] opened 2021-02-11 02:23 UTC
## Description
I am unable to integrate geofire through cocoapods on firebase 7.0.0 and up. 

`pod install` error below
```
[!] CocoaPods could not find compatible versions for pod "Firebase/Database":
  In snapshot (Podfile.lock):
    Firebase/Database (= 7.2.0-M1)

  In Podfile:
    GeoFire/Utils was resolved to 4.1.0, which depends on
      Firebase/Database (~> 6.0)

Specs satisfying the `Firebase/Database (= 7.2.0-M1), Firebase/Database (~> 6.0)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by mark-baumann** [comment] 2021-02-12 11:24
"pod update" should solve your problem

**Comment by mark-baumann** [comment] 2021-02-12 17:23
I reproduced your issue. I had the same problem several times........

**Comment by thatguyhampton** [comment] 2021-02-12 17:58
@mark-baumann I was able to fix it locally by pulling the repository as a local podspec and updating the dependency in the `GeoFire.podspec` from 
```
  s.ios.dependency  'Firebase/Database', '~> 6.0'
```
```
s.ios.dependency  'Firebase/Database', '~> 7.0'
```

**Comment by mark-baumann** [comment] 2021-02-12 21:31
Nice! Maybe you can help me with my issue? https://github.com/firebase/geofire-objc/issues/143

**Comment by frios** [comment] 2021-02-18 21:58
Any timeline when we can expect GeoFire to be updated?

**Comment by parkskier426** [comment] 2021-03-11 17:05
Updating all of my projects Google packages to null safety has sent me through dependency hell trying to get everything compatible. I think this is my last package. @thatguyhampton I'm not familiar with pulling the repository as a local podspec. Would you mind pointing me in the right direction?

**Comment by parkskier426** [comment] 2021-03-11 19:51
Wow, what a PITA. I was able to get it working. I had to create a private podspec repo, and the fixed version to its own repo with a custom version tag, update my podspec to use the new version tag, and update the podfile to point to the private source. Maybe there's an easier way, but I couldn't get anything else working.

**Comment by marcuslindemannrohden** [comment] 2021-03-21 04:15
Hey @parkskier426  could you please give a more detailed explanation of how you did it and post your podspec? I'm having exactly the same issue...
Thank you!

**Comment by marcuslindemannrohden** [comment] 2021-03-21 06:46
I have submitted a pull request with the updated podspecs. Hope it helps...

#147

**Comment by gregor9494** [comment] 2021-03-28 09:20
+1 Can someone upload a version with firebase/database 7 ?

**Comment by parkskier426** [comment] 2021-03-28 10:53
> +1 Can someone upload a version with firebase/database 7 ?

It looks like these changes were merged into master 5 days ago. You should be good to go.

**Closed** 2021-03-29 18:53 UTC
